{"name": "test_div[int_case_fail]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 100.0 == 200", "trace": "self = <hogwarts_learn.Test_pytestcase1.test_zuoye2.TestCalculator object at 0x000002BD6DB52BE0>\nget_calc = <Cal_method.funcal.Calculator object at 0x000002BD6DAAF100>, a = 100, b = 1, expect = 200\n\n    @pytest.mark.run(order=4)\n    @pytest.mark.parametrize('a,b,expect',get_datas()['DIV']['parametrize'], ids=get_datas()['DIV']['ids'])\n    def test_div(self,get_calc, a, b, expect):\n        result = get_calc.div(a, b)\n>       assert result == expect\nE       assert 100.0 == 200\n\ntest_zuoye2.py:33: AssertionError"}, "parameters": [{"name": "a", "value": "100"}, {"name": "b", "value": "1"}, {"name": "expect", "value": "200"}], "start": 1603203147048, "stop": 1603203147048, "uuid": "4a2b1d7a-c1e9-4900-9c03-be90593d67da", "historyId": "1a9491601f20e0797d8d4c72d17390cb", "testCaseId": "f553cc62ff7f1281a430cded7b91b323", "fullName": "test_zuoye2.TestCalculator#test_div", "labels": [{"name": "tag", "value": "run(order=4)"}, {"name": "suite", "value": "test_zuoye2"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "LZP"}, {"name": "thread", "value": "20824-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_zuoye2"}]}